FROM node:22-alpine AS build
WORKDIR /app
COPY frontend/package*.json ./
RUN npm install
COPY frontend ./
ENV VITE_STAFF_SITE=true
RUN npm run build

FROM nginx:1.27-alpine
COPY frontend/nginx.staff.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
