import React,{useEffect,useState} from 'react'
import ApplicantActions from './ApplicantActions'

const API='/api/v1'
const statusText:Record<string,[string,string]>={NEW:['Мы получили твоё обращение','Мы получили ваше обращение'],ASSIGNED:['Передали твоё обращение специалисту','Передали ваше обращение специалисту'],IN_PROGRESS:['Специалист разбирается в ситуации','Специалист разбирается в ситуации'],WAITING_FOR_APPLICANT:['Нужен твой ответ','Нужен ваш ответ'],ANSWER_READY:['Рекомендации готовы','Рекомендации готовы'],RETURNED:['Мы вернулись к твоей ситуации','Мы вернулись к вашей ситуации'],COMPLETED:['Рады, что смогли помочь','Рады, что смогли помочь'],REJECTED:['Сервис не сможет помочь с этой ситуацией','Сервис не сможет помочь с этой ситуацией'],CLOSED_NO_RESPONSE:['Обращение закрыто, но можно написать снова','Обращение закрыто, но можно написать снова']}
const crisisWords=['суицид','самоуб','покончить с собой','убить себя','не хочу жить','хочу умереть','умереть','лучше умер','смерти','повеситься','выпрыгнуть','порезать себя','навредить себе','угрожает убить','угрожают убить','меня бьют','избивают','изнасил']
const hasCrisis=(value:string)=>crisisWords.some(word=>value.toLowerCase().includes(word))
export default function Appeal({Shell,Crisis}:{Shell:any;Crisis:any}){
 const [data,setData]=useState<any>(),[message,setMessage]=useState(''),[files,setFiles]=useState<File[]>([]),[reason,setReason]=useState(''),[notice,setNotice]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false)
 async function load(){const r=await fetch(`${API}/my-appeal`,{credentials:'include'});if(r.ok){setData(await r.json());setError('')}else setError('Сессия завершена. Открой обращение по коду.')}
 useEffect(()=>{load()},[])
 function chooseFiles(list:FileList|null){const next=Array.from(list||[]);if(next.length>5||next.some(f=>f.size>10*1024*1024||!['image/jpeg','image/png'].includes(f.type))){setError('Можно приложить до 5 изображений JPG или PNG, каждое до 10 МБ');return}setFiles(next);setError('')}
 async function send(){if((!message.trim()&&!files.length)||busy)return;setBusy(true);setError('');const payload={body:message.trim()};let request:any={method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)};if(files.length){const form=new FormData();form.append('payload',JSON.stringify(payload));files.forEach(file=>form.append('files',file));request={method:'POST',credentials:'include',body:form}}const r=await fetch(`${API}/my-appeal/messages`,request);if(r.ok){setMessage('');setFiles([]);await load()}else setError((await r.json()).error?.message||'Не удалось отправить сообщение');setBusy(false)}
 async function reassign(){const r=await fetch(`${API}/my-appeal/reassignment-requests`,{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({reason})});if(r.ok){setReason('');setNotice('Просьба отправлена оператору')}else setError((await r.json()).error?.message||'Не удалось отправить просьбу')}
 async function remove(){if(!confirm('Удалить обращение без возможности восстановления? Код доступа и чат перестанут работать.'))return;await fetch(`${API}/my-appeal`,{method:'DELETE',credentials:'include'});location.href='/'}
 if(error&&!data)return <Shell><p className="error">{error}</p></Shell>;if(!data)return <Shell><p>Загружаем…</p></Shell>;const adult=data.appeal.applicantType!=='STUDENT',completed=data.appeal.status==='COMPLETED'
 const history=data.appeal.statusHistory||[],attachments=data.appeal.attachments||[],label=(status:string)=>statusText[status]?.[adult?1:0]||status
 return <Shell><section className="appeal"><div className="status"><span>{data.appeal.publicId}</span><b>{label(data.appeal.status)}</b></div><ol className="status-line">{history.map((h:any,i:number)=><li className={i===history.length-1?'current':''} key={i}><i/><div><b>{label(h.status)}</b><small>{new Date(h.createdAt).toLocaleString('ru-RU')}{h.reason?` · ${h.reason}`:''}</small></div></li>)}</ol>{(data.appeal.crisisFlag||hasCrisis(message))&&<Crisis/>}<article><span className="eyebrow">{adult?'ВАША ИСТОРИЯ':'ТВОЯ ИСТОРИЯ'}</span><p>{data.appeal.body}</p>{attachments.length>0&&<div className="attachment-list"><b>Приложенные скриншоты</b>{attachments.map((a:any)=><a target="_blank" rel="noreferrer" href={`${API}/my-appeal/attachments/${a.id}`} key={a.id}>↗ {a.fileName}</a>)}</div>}</article><div className="timeline">{data.messages.map((m:any)=><div className={'bubble '+m.authorType.toLowerCase()} key={m.id}><small>{m.authorType==='APPLICANT'?(adult?'Вы':'Ты'):m.authorName}</small><p>{m.body}</p>{(m.attachments||[]).map((a:any)=><a className="chat-file" target="_blank" rel="noreferrer" href={`${API}/my-appeal/attachments/${a.id}`} key={a.id}>↗ {a.fileName}</a>)}</div>)}</div>{!completed&&<div className="composer"><textarea value={message} onChange={e=>setMessage(e.target.value)} placeholder="Можно дополнить обращение или ответить специалисту"/><label className="chat-upload">＋ Приложить скриншоты<input type="file" accept="image/jpeg,image/png" multiple onChange={e=>chooseFiles(e.target.files)}/></label>{files.length>0&&<small>{files.map(f=>f.name).join(', ')}</small>}<button className="primary" disabled={busy||(!message.trim()&&!files.length)} onClick={send}>{busy?'Отправляем…':'Отправить сообщение'}</button></div>}<ApplicantActions status={data.appeal.status} returnCount={data.appeal.returnCount} feedback={data.appeal.feedback} adult={adult} reload={load}/>{!completed&&<details><summary>Попросить другого эксперта</summary><p>{adult?'Напишите, почему вы хотите продолжить разговор с другим специалистом. Причину увидит оператор.':'Напиши, почему хочется продолжить разговор с другим специалистом. Причину увидит оператор.'}</p><textarea value={reason} onChange={e=>setReason(e.target.value)} placeholder={adult?'Что вы хотели бы изменить?':'Что хотелось бы изменить?'}/><button className="secondary" disabled={reason.trim().length<3} onClick={reassign}>Отправить просьбу оператору</button>{notice&&<p>{notice}</p>}</details>}<details className="privacy"><summary>Приватность и удаление</summary><p><b>Завершение</b> сохраняет чат и код доступа — общение можно возобновить. <b>Удаление</b> необратимо закрывает доступ и удаляет содержимое; в аналитике остаётся только обезличенный факт со статусом «Удалено».</p><button className="danger" onClick={remove}>Удалить обращение навсегда</button></details>{error&&<p className="error">{error}</p>}</section></Shell>
}
