import React,{useEffect,useState} from 'react'
import './workspace.css'
import AdminQuestions from './AdminQuestions'

const API='/api/v1'
const roles:Record<string,string>={ADMIN:'Администратор',OPERATOR:'Оператор',EXPERT:'Эксперт'}
const statuses:Record<string,string>={NEW:'Новое',ASSIGNED:'Назначено',IN_PROGRESS:'В работе',WAITING_FOR_APPLICANT:'Ожидает заявителя',ANSWER_READY:'Ответ готов',RETURNED:'На доработке',COMPLETED:'Завершено',REJECTED:'Отклонено',CLOSED_NO_RESPONSE:'Закрыто без ответа'}
const priorities:Record<string,string>={LOW:'Низкий',STANDARD:'Обычный',URGENT:'Срочный'}
const actions:Record<string,string>={reply:'Ответы',note:'Заметки',request:'Запросы',assign:'Назначения',coexecutor:'Соисполнители',priority:'Приоритеты',status:'Смена статуса',reject_request:'Отклонение запроса'}
async function api(path:string,body?:any,method?:string){const r=await fetch(API+path,{credentials:'include',method:method||(body?'POST':'GET'),headers:{'Content-Type':'application/json','X-Molva-Request':'1'},body:body?JSON.stringify(body):undefined});if(!r.ok){const d=await r.json().catch(()=>({}));throw new Error(d.error?.message||'Не удалось выполнить действие')}return r.status===204?null:r.json()}
async function chatApi(path:string,body:string,files:File[]){const payload={body:body.trim()},form=new FormData();form.append('payload',JSON.stringify(payload));files.forEach(file=>form.append('files',file));const r=await fetch(API+path,{credentials:'include',method:'POST',headers:{'X-Molva-Request':'1'},body:form});if(!r.ok){const d=await r.json().catch(()=>({}));throw new Error(d.error?.message||'Не удалось отправить сообщение')}}
const date=(v:string)=>new Date(v).toLocaleDateString('ru-RU',{day:'numeric',month:'short'})

export default function StaffWorkspace(){
 const [user,setUser]=useState<any>(null),[ready,setReady]=useState(false),[page,setPage]=useState('dashboard'),[error,setError]=useState(''),[cases,setCases]=useState<any[]>([]),[experts,setExperts]=useState<any[]>([]),[selected,setSelected]=useState<any>(null),[detail,setDetail]=useState<any>(null),[search,setSearch]=useState(''),[filter,setFilter]=useState(''),[priorityFilter,setPriorityFilter]=useState(''),[categoryFilter,setCategoryFilter]=useState(''),[busy,setBusy]=useState(false)
 async function refresh(){const [c,e]=await Promise.all([api('/staff/cases'),api('/staff/experts')]);setCases(c.items||[]);setExperts(e.items||[])}
 useEffect(()=>{api('/staff/me').then(setUser).catch(()=>{}).finally(()=>setReady(true))},[])
 useEffect(()=>{if(user)refresh().catch(e=>setError(e.message))},[user])
 async function open(c:any){setSelected(c);setDetail(null);try{setDetail(await api('/staff/cases/'+c.id))}catch(e:any){setError(e.message)}}
 async function act(data:any){if(!selected||busy)return;setBusy(true);setError('');try{await api('/staff/cases/'+selected.id+'/actions',data);const c=await api('/staff/cases');setCases(c.items);const next=c.items.find((v:any)=>v.id===selected.id);if(next){await open(next)}else{setSelected(null);setDetail(null)}}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 async function sendChat(body:string,files:File[]){if(!selected||busy)return false;setBusy(true);setError('');try{await chatApi('/staff/cases/'+selected.id+'/messages',body,files);const c=await api('/staff/cases');setCases(c.items);const next=c.items.find((v:any)=>v.id===selected.id);if(next)await open(next);return true}catch(e:any){setError(e.message);return false}finally{setBusy(false)}}
 if(!ready)return <div className="mw-loading">Загружаем кабинет…</div>
 if(!user)return <Login onLogin={setUser}/>
 const admin=user.role==='ADMIN',expert=user.role==='EXPERT'
 const active=cases.filter(c=>!['COMPLETED','REJECTED','CLOSED_NO_RESPONSE'].includes(c.status))
 const filtered=cases.filter(c=>(!filter||c.status===filter)&&(!priorityFilter||c.priority===priorityFilter)&&(!categoryFilter||c.category===categoryFilter)&&`${c.public_id} ${c.category}`.toLowerCase().includes(search.toLowerCase()))
 const categoryOptions=[...new Set(cases.map(c=>c.category))]
 const nav=[['dashboard','Обзор','◫'],['cases',expert?'Мои обращения':'Обращения','▤'],['statistics',admin?'Аналитика':'Моя статистика','▥'],...(admin?[['people','Сотрудники','♙'],['categories','Маршрутизация','⇄'],['questions','Опросник','☷'],['audit','Журнал','≡']]:[])]
 return <div className="mw"><aside className="mw-sidebar"><a className="mw-brand" href="/staff">молва<span>рабочее пространство</span></a><nav>{nav.map(([id,label,icon])=><button key={id} className={page===id?'active':''} onClick={()=>{setPage(id);setError('')}}><span>{icon}</span>{label}{id==='cases'&&<small>{active.length}</small>}</button>)}</nav><div className="mw-profile"><div className="mw-avatar">{user.name[0]}</div><b>{user.name}<small>{roles[user.role]}</small></b><button title="Выйти" onClick={()=>api('/staff/logout',{}).then(()=>{setUser(null);setSelected(null);setPage('dashboard')}).catch(e=>setError(e.message))}>↗</button></div></aside><div className="mw-main"><header className="mw-header"><div><span>МОЛВА / {roles[user.role].toUpperCase()}</span><h1>{nav.find(n=>n[0]===page)?.[1]}</h1></div><button className="mw-btn" onClick={()=>refresh().catch(e=>setError(e.message))}>↻ Обновить</button></header>{error&&<div role="alert" className="mw-error">{error}<button onClick={()=>setError('')}>×</button></div>}
 {page==='dashboard'&&<><section className="mw-welcome"><div><span className="mw-eyebrow">РАБОЧИЙ ДЕНЬ</span><h2>{user.name}, добро пожаловать</h2><p>{admin?'Управляйте командой, нагрузкой и правилами работы сервиса.':expert?'Здесь собраны обращения, в которых нужна ваша помощь.':'Помогите каждому обращению попасть к подходящему специалисту.'}</p></div><button className="mw-primary" onClick={()=>setPage('cases')}>Открыть обращения →</button></section><div className="mw-metrics">{[['В работе',active.length,'Активные обращения'],['Требуют внимания',active.filter(c=>c.priority==='URGENT'||c.crisis_flag).length,'Срочные и с сигналом риска'],['Просрочено',cases.filter(c=>c.overdue||c.stale).length,'Без реакции дольше нормы'],['Завершено',cases.filter(c=>c.status==='COMPLETED').length,'Помощь получена']].map(([title,value,hint])=><article key={title}><span>{title}</span><strong>{value}</strong><small>{hint}</small></article>)}</div>{!expert&&cases.some(c=>c.crisis_flag&&!['COMPLETED','REJECTED'].includes(c.status))&&<section className="mw-panel mw-crisis-block"><div className="mw-section-head"><div><h2>Требуют немедленного внимания</h2><p className="mw-muted">Кризисные маркеры обнаружены системой. Приоритет подтверждает оператор.</p></div></div><CaseTable items={cases.filter(c=>c.crisis_flag&&!['COMPLETED','REJECTED'].includes(c.status))} onOpen={c=>{setPage('cases');open(c)}}/></section>}<section className="mw-panel"><div className="mw-section-head"><h2>Сейчас в фокусе</h2><button className="mw-link" onClick={()=>setPage('cases')}>Все обращения →</button></div><CaseTable items={active.slice(0,6)} onOpen={c=>{setPage('cases');open(c)}}/></section></>}
 {page==='cases'&&<><div className="mw-toolbar"><input placeholder="Поиск по номеру или категории" value={search} onChange={e=>setSearch(e.target.value)}/><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="">Все статусы</option>{Object.entries(statuses).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select><select value={priorityFilter} onChange={e=>setPriorityFilter(e.target.value)}><option value="">Все приоритеты</option>{Object.entries(priorities).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select><select value={categoryFilter} onChange={e=>setCategoryFilter(e.target.value)}><option value="">Все категории</option>{categoryOptions.map(c=><option key={c} value={c}>{c}</option>)}</select><span>{filtered.length} обращений</span></div><div className={'mw-cases '+(selected?'with-detail':'')}><section className="mw-panel"><CaseTable items={filtered} selected={selected?.id} onOpen={open}/></section>{selected&&<section className="mw-panel mw-detail"><div className="mw-section-head"><div><small>{selected.public_id}</small><h2>{selected.category}</h2></div><button className="mw-link" onClick={()=>setSelected(null)}>Закрыть ×</button></div><div className="mw-tags"><span className={'mw-badge '+selected.status}>{statuses[selected.status]}</span><span className={'mw-badge '+selected.priority}>{priorities[selected.priority]}</span>{selected.crisis_flag&&<span className="mw-badge crisis-mark">Кризисный сигнал</span>}{selected.stale&&<span className="mw-badge">Нет ответа &gt; 24 ч</span>}</div><p className="mw-muted">Специалисты: {selected.experts.map((e:any)=>e.name+(e.kind==='COEXECUTOR'?' (соисполнитель)':'')).join(', ')||'не назначены'}</p>{!detail?<p>Загружаем…</p>:<><CaseContents role={user.role} detail={detail}/><CaseControls key={selected.id} role={user.role} selected={selected} detail={detail} experts={experts} act={act} sendChat={sendChat} busy={busy}/></>}</section>}</div></>}
 {page==='statistics'&&<Statistics role={user.role}/>}
 {page==='people'&&admin&&<People selfId={user.id}/>}
 {page==='categories'&&admin&&<RoutingAdmin experts={experts}/>} 
 {page==='questions'&&admin&&<AdminQuestions/>}
 {page==='audit'&&admin&&<AuditLog/>}
 </div></div>
}
function Login({onLogin}:{onLogin:(u:any)=>void}){const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);return <div className="mw-login"><section><a className="mw-brand" href="/staff">молва</a><span className="mw-eyebrow">ВНУТРЕННИЙ КАБИНЕТ</span><h1>Рады видеть вас</h1><p>Войдите с учётной записью сотрудника.</p><form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{onLogin(await api('/staff/login',{email,password}))}catch(e:any){setError(e.message)}finally{setBusy(false)}}}><label>Рабочая почта<input type="email" autoComplete="username" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Пароль<input type="password" autoComplete="current-password" required value={password} onChange={e=>setPassword(e.target.value)}/></label>{error&&<p className="mw-error">{error}</p>}<button className="mw-primary" disabled={busy}>{busy?'Входим…':'Войти в кабинет →'}</button></form><small>Учётную запись создаёт администратор вашей организации.</small></section><aside><h2>Каждое обращение<br/>заслуживает внимания.</h2><p>Одна команда. Понятные роли.<br/>Бережная работа с каждой историей.</p></aside></div>}
function wait(v:number){if(v<3600)return `${Math.max(1,Math.floor(v/60))} мин`;if(v<86400)return `${Math.floor(v/3600)} ч`;return `${Math.floor(v/86400)} д`}
function CaseTable({items,onOpen,selected}:{items:any[];onOpen:(c:any)=>void;selected?:string}){return <div className="mw-table-wrap"><table><thead><tr><th>Обращение</th><th>Статус</th><th>Приоритет</th><th>Ожидание</th></tr></thead><tbody>{items.map(c=><tr className={(selected===c.id?'selected ':'')+(c.crisis_flag?'crisis-row ':'')+(c.overdue?'overdue-row':'')} key={c.id}><td><button className="mw-case-link" onClick={()=>onOpen(c)}><b>{c.public_id}</b><span>{c.category}</span></button></td><td><span className={'mw-badge '+c.status}>{statuses[c.status]}</span></td><td><span className={'mw-priority '+c.priority}>● {priorities[c.priority]}</span></td><td>{wait(c.waiting_seconds||0)}{c.overdue&&<small className="mw-block">просрочено</small>}</td></tr>)}</tbody></table>{!items.length&&<div className="mw-empty">Здесь пока нет обращений</div>}</div>}
function CaseContents({role,detail}:{role:string;detail:any}){return <>{role!=='ADMIN'&&<section className="mw-story"><h3>Исходное обращение</h3><p>{detail.body}</p>{detail.answerItems?.length>0&&<details><summary>Ответы на опросник</summary>{detail.answerItems.map((item:any)=><p key={item.code}><b>{item.question}: </b>{Array.isArray(item.answer)?item.answer.join(', '):String(item.answer)}</p>)}</details>}{detail.attachments?.length>0&&<div className="mw-attachments"><h4>Вложения к обращению</h4>{detail.attachments.map((a:any)=><a target="_blank" rel="noreferrer" href={`${API}/staff/cases/${detail.caseId||''}/attachments/${a.id}`} key={a.id}>↗ {a.file_name}</a>)}</div>}</section>}{role==='OPERATOR'&&detail.feedback&&<section className="mw-feedback"><h3>Оценка и обратная связь</h3>{detail.feedback.rating&&<p>Оценка: <b>{detail.feedback.rating} из 5</b></p>}{detail.feedback.comment&&<p>{detail.feedback.comment}</p>}{detail.feedback.complaint&&<div className="mw-warning"><b>Жалоба на специалиста</b><p>{detail.feedback.complaintText}</p></div>}</section>}{detail.canChat&&<><h3>{role==='OPERATOR'?'Уточнения до назначения':'Переписка с заявителем'}</h3><div className="mw-chat">{(detail.messages||[]).map((m:any)=><article className={m.author_type!=='APPLICANT'?'outgoing':''} key={m.id}><small>{m.author_name} · {date(m.created_at)}</small><p>{m.body}</p>{(m.attachments||[]).map((a:any)=><a className="mw-chat-file" target="_blank" rel="noreferrer" href={`${API}/staff/cases/${detail.caseId}/attachments/${a.id}`} key={a.id}>↗ {a.file_name}</a>)}</article>)}{!detail.messages?.length&&<p className="mw-muted">Диалог пока пуст</p>}</div></>}{role==='EXPERT'&&<details className="mw-notes"><summary>Внутренние заметки · {detail.notes?.length||0}</summary>{detail.notes?.map((n:any)=><article key={n.id}><small>{n.author_name}</small><p>{n.body}</p></article>)}</details>}</>}
function CaseControls({role,selected,detail,experts,act,sendChat,busy}:any){const [body,setBody]=useState(''),[files,setFiles]=useState<File[]>([]),[fileError,setFileError]=useState(''),[mode,setMode]=useState('reply'),[expertId,setExpertId]=useState(detail.routingHint?.expert_id||''),[status,setStatus]=useState(''),[priority,setPriority]=useState(selected.priority),[reason,setReason]=useState('');const expert=role==='EXPERT',admin=role==='ADMIN',operator=role==='OPERATOR';const done=['COMPLETED','REJECTED','CLOSED_NO_RESPONSE'].includes(selected.status);let targets=['IN_PROGRESS','WAITING_FOR_APPLICANT','ANSWER_READY'];if(operator)targets.push('COMPLETED','RETURNED','REJECTED','CLOSED_NO_RESPONSE');function chooseFiles(list:FileList|null){const next=Array.from(list||[]);if(next.length>5||next.some(f=>f.size>10*1024*1024||!['image/jpeg','image/png'].includes(f.type))){setFileError('До 5 JPG/PNG, каждый не больше 10 МБ');return}setFiles(next);setFileError('')}async function submitChat(){if(await sendChat(body,files)){setBody('');setFiles([])}}return <div className="mw-controls"><fieldset disabled={busy}>{!expert&&<><h3>Распределение и приоритет</h3>{detail.routingHint&&<div className={'mw-routing-hint '+(detail.routingHint.overloaded?'warning':'')}><b>Подсказка маршрутизации: {detail.routingHint.group_name}</b><p>{detail.routingHint.overloaded?'Все специалисты группы достигли лимита — обращение остаётся у оператора.':detail.routingHint.expert_name?`Свободнее всего: ${detail.routingHint.expert_name} (${detail.routingHint.active_count} активных из ${detail.routingHint.max_active_per_expert}).`:'В группе нет доступных специалистов.'}</p></div>}{admin&&<textarea value={reason} onChange={e=>setReason(e.target.value)} placeholder="Причина административного изменения — обязательна"/>}<div className="mw-inline"><select aria-label="Приоритет" value={priority} onChange={e=>setPriority(e.target.value)}>{Object.entries(priorities).map(([k,v])=><option value={k} key={k}>{v}</option>)}</select><button className="mw-btn" disabled={admin&&reason.trim().length<3} onClick={()=>act({action:'priority',value:priority,body:reason})}>Сохранить</button></div><div className="mw-inline"><select aria-label="Эксперт" value={expertId} onChange={e=>setExpertId(e.target.value)}><option value="">Выберите эксперта</option>{experts.map((e:any)=><option value={e.id} key={e.id}>{e.name} · {e.active_count||0} активных</option>)}</select><button className="mw-primary" disabled={!expertId||done||(admin&&reason.trim().length<3)} onClick={()=>act({action:'assign',expertId,body:reason})}>Назначить</button></div></>}
 <h3>Статус обращения</h3>{operator&&status==='REJECTED'&&<textarea value={reason} onChange={e=>setReason(e.target.value)} placeholder="Почему сервис не может помочь и куда можно обратиться"/>}<div className="mw-inline"><select aria-label="Новый статус" value={status} onChange={e=>setStatus(e.target.value)}><option value="">Выберите действие</option>{targets.filter(t=>{const from=selected.status;if(t===from)return false;if(admin)return !['COMPLETED','REJECTED','CLOSED_NO_RESPONSE'].includes(t);if(t==='RETURNED')return ['ANSWER_READY','COMPLETED'].includes(from);if(t==='COMPLETED')return from==='ANSWER_READY';if(done)return false;if(['REJECTED','CLOSED_NO_RESPONSE'].includes(t))return true;if(t==='IN_PROGRESS')return ['ASSIGNED','RETURNED','WAITING_FOR_APPLICANT','ANSWER_READY'].includes(from);return ['ASSIGNED','IN_PROGRESS','RETURNED','WAITING_FOR_APPLICANT'].includes(from)}).map(t=><option key={t} value={t}>{statuses[t]}</option>)}</select><button className="mw-btn" disabled={!status||((admin||status==='REJECTED')&&reason.trim().length<3)} onClick={()=>act({action:'status',value:status,body:reason})}>Применить</button></div>
 {operator&&detail.canChat&&!done&&<div className="mw-operator-close"><h3>Уточнить у заявителя</h3><p className="mw-muted">До назначения эксперта можно задать наводящий вопрос или запросить скриншот. После назначения чат оператора будет закрыт.</p><div className="mw-quick-prompts"><button type="button" className="mw-link" onClick={()=>setBody('Пожалуйста, уточните, когда и где это произошло.')}>Уточнить обстоятельства</button><button type="button" className="mw-link" onClick={()=>setBody('Если вам удобно, приложите, пожалуйста, скриншот — перед сохранением мы удалим метаданные.')}>Запросить скриншот</button></div><textarea value={body} onChange={e=>setBody(e.target.value)} placeholder="Бережный вопрос заявителю"/><label className="mw-file-button">＋ Приложить файл<input type="file" accept="image/jpeg,image/png" multiple onChange={e=>chooseFiles(e.target.files)}/></label>{files.length>0&&<small className="mw-block">{files.map(f=>f.name).join(', ')}</small>}{fileError&&<p className="mw-error">{fileError}</p>}<div className="mw-inline"><button className="mw-primary" disabled={!body.trim()&&!files.length} onClick={submitChat}>Отправить в чат</button>{selected.status==='NEW'&&<button className="mw-btn" disabled={body.trim().length<3} onClick={()=>act({action:'operator_reply_close',body})}>Ответить и завершить</button>}</div></div>}
 {expert&&!done&&<><div className="mw-tabs">{[['reply','Ответ'],['note','Заметка'],['TRANSFER','Передача'],['COEXECUTOR','Соисполнитель']].map(([k,v])=><button key={k} className={mode===k?'active':''} onClick={()=>{setMode(k);setFiles([]);setFileError('')}}>{v}</button>)}</div><textarea placeholder={mode==='reply'?'Напишите ответ заявителю…':mode==='note'?'Заметку увидят только назначенные эксперты…':'Обоснование запроса для оператора…'} value={body} onChange={e=>setBody(e.target.value)}/>{mode==='reply'&&<><label className="mw-file-button">＋ Приложить файл<input type="file" accept="image/jpeg,image/png" multiple onChange={e=>chooseFiles(e.target.files)}/></label>{files.length>0&&<small className="mw-block">{files.map(f=>f.name).join(', ')}</small>}{fileError&&<p className="mw-error">{fileError}</p>}</>}<button className="mw-primary" disabled={!body.trim()&&!(mode==='reply'&&files.length)} onClick={async()=>{if(mode==='reply')await submitChat();else await act({action:mode==='note'?'note':'request',value:mode,body})}}>Отправить {mode==='reply'?'ответ':mode==='note'?'заметку':'запрос'}</button></>}
 {!!detail.requests?.length&&<section><h3>Запросы на смену команды</h3>{detail.requests.map((r:any)=><article className="mw-request" key={r.id}><b>{r.kind==='COEXECUTOR'?'Подключить соисполнителя':'Передать обращение'}</b><small>{r.requested_by==='APPLICANT'?'Просьба заявителя':'Запрос эксперта'} · {r.status==='NEW'?'Ожидает решения':r.status==='APPROVED'?'Выполнен':'Отклонён'}</small>{r.reason&&<p>{r.reason}</p>}{!expert&&r.status==='NEW'&&<div className="mw-inline"><button className="mw-primary" disabled={!expertId||done} onClick={()=>act({action:r.kind==='COEXECUTOR'?'coexecutor':'assign',expertId,requestId:r.id})}>Назначить выбранного</button><button className="mw-btn" onClick={()=>act({action:'reject_request',requestId:r.id})}>Отклонить</button></div>}</article>)}</section>}</fieldset></div>}

function duration(v:number){if(!v)return '—';if(v<3600)return `${Math.round(v/60)} мин`;if(v<86400)return `${(v/3600).toFixed(1)} ч`;return `${(v/86400).toFixed(1)} д`}
function Statistics({role}:{role:string}){
 const [data,setData]=useState<any[]>([]),[overview,setOverview]=useState<any>({}),[error,setError]=useState('')
 useEffect(()=>{setData([]);setError('');api('/staff/statistics').then(d=>{setData(d.items||[]);setOverview(d.overview||{})}).catch(e=>setError(e.message))},[])
 const summary=overview.summary||{},total=Number(summary.total??data.reduce((sum,row)=>sum+Number(row.count||0),0)),urgent=Number(summary.urgent??data.reduce((sum,row)=>sum+Number(row.urgentCount||0),0)),returned=Number(summary.returned??data.reduce((sum,row)=>sum+Number(row.returnedCount||0),0))
 return <section className="mw-panel mw-pad"><div className="mw-section-head"><div><h2>{role==='ADMIN'?'Общая аналитика':'Статистика моей работы'}</h2><p className="mw-muted">Только обезличенные показатели — без текстов, контактов и переписки.</p></div><div className="mw-inline"><a className="mw-btn" href={API+'/staff/statistics?format=csv'}>↓ CSV</a><a className="mw-btn" href={API+'/staff/statistics?format=xlsx'}>↓ XLSX</a></div></div>{role==='ADMIN'&&<><div className="mw-metrics"><article><span>Обращений</span><strong>{total}</strong><small>За доступный период</small></article><article><span>Доля срочных</span><strong>{total?Math.round(urgent/total*100):0}%</strong><small>Приоритет подтверждён человеком</small></article><article><span>Доля возвратов</span><strong>{total?Math.round(returned/total*100):0}%</strong><small>Ответ потребовал доработки</small></article><article><span>Среднее до ответа</span><strong>{duration(summary.averageFirstResponseSeconds)}</strong><small>От создания обращения</small></article></div><div className="mw-analytics-grid"><article><h3>Типы заявителей</h3>{(overview.byApplicantType||[]).map((v:any)=><p key={v.label}><span>{({STUDENT:'Школьники',PARENT:'Родители',TEACHER:'Педагоги'} as any)[v.label]||v.label}</span><b>{v.count}</b></p>)}</article><article><h3>Статусы</h3>{(overview.byStatus||[]).map((v:any)=><p key={v.label}><span>{statuses[v.label]||v.label}</span><b>{v.count}</b></p>)}</article><article><h3>Нагрузка команды</h3>{(overview.staffLoad||[]).map((v:any)=><p key={v.label}><span>{v.label}</span><b>{v.count}</b></p>)}</article></div></>}{error&&<p className="mw-error">{error}</p>}<div className="mw-table-wrap"><table><thead><tr><th>Дата</th><th>{role==='ADMIN'?'Категория':'Действие'}</th><th>Количество</th>{role==='ADMIN'&&<><th>Срочных</th><th>Возвратов</th><th>До принятия</th><th>До ответа</th><th>До закрытия</th></>}</tr></thead><tbody>{data.map((r,i)=><tr key={i}><td>{date(r.day)}</td><td>{role==='ADMIN'?r.category:actions[r.action]||r.action}</td><td>{r.count}</td>{role==='ADMIN'&&<><td>{r.urgentCount}</td><td>{r.returnedCount}</td><td>{duration(r.averageAcceptanceSeconds)}</td><td>{duration(r.averageFirstResponseSeconds)}</td><td>{duration(r.averageResolutionSeconds)}</td></>}</tr>)}</tbody></table></div>{!data.length&&!error&&<div className="mw-empty">Нет данных для отображения{role==='ADMIN'?' с учётом минимального размера группы':''}.</div>}</section>
}
function People({selfId}:{selfId:string}){const [items,setItems]=useState<any[]>([]),[form,setForm]=useState<any>(null),[error,setError]=useState('');async function load(){setItems((await api('/admin/staff')).items)}useEffect(()=>{load().catch(e=>setError(e.message))},[]);async function save(e:React.FormEvent){e.preventDefault();try{const {id,email,displayName,role,active,password}=form;await api('/admin/staff'+(id?'/'+id:''),id?{email,displayName,role,active,password}:{email,displayName,role,password},id?'PUT':'POST');setForm(null);await load()}catch(e:any){setError(e.message)}}return <section className="mw-panel mw-pad"><div className="mw-section-head"><div><h2>Команда</h2><p className="mw-muted">Роль определяет действия сотрудника и доступ к данным.</p></div><button className="mw-primary" onClick={()=>setForm({email:'',displayName:'',role:'OPERATOR',active:true,password:''})}>+ Добавить сотрудника</button></div>{error&&<p className="mw-error">{error}</p>}{form&&<form className="mw-editor" onSubmit={save}><h3>{form.id?'Настройки сотрудника':'Новый сотрудник'}</h3><label>Имя для заявителя<input required value={form.displayName} onChange={e=>setForm({...form,displayName:e.target.value})}/></label><label>Почта<input required type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>Роль<select value={form.role} disabled={form.id===selfId} onChange={e=>setForm({...form,role:e.target.value})}>{Object.entries(roles).filter(([k])=>form.id||k!=='ADMIN').map(([k,v])=><option value={k} key={k}>{v}</option>)}</select></label><label>{form.id?'Новый пароль (необязательно)':'Пароль'}<input type="password" minLength={12} required={!form.id} value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></label>{form.id&&<label className="mw-check"><input type="checkbox" disabled={form.id===selfId} checked={form.active} onChange={e=>setForm({...form,active:e.target.checked})}/>Учётная запись активна</label>}<div className="mw-inline"><button className="mw-primary">Сохранить</button><button type="button" className="mw-btn" onClick={()=>setForm(null)}>Отмена</button></div></form>}<table><thead><tr><th>Сотрудник</th><th>Роль</th><th>Доступ</th><th></th></tr></thead><tbody>{items.map(u=><tr key={u.id}><td><b>{u.displayName}</b><small className="mw-block">{u.email}</small></td><td>{roles[u.role]}</td><td><span className="mw-badge">{u.active?'Активен':'Заблокирован'}</span></td><td><button className="mw-link" onClick={()=>setForm({...u,password:''})}>Настроить</button></td></tr>)}</tbody></table></section>}
function Categories({experts}:{experts:any[]}){const [items,setItems]=useState<any[]>([]),[form,setForm]=useState<any>(null),[error,setError]=useState('');async function load(){setItems((await api('/admin/categories')).items)}useEffect(()=>{load().catch(e=>setError(e.message))},[]);return <section className="mw-panel mw-pad"><div className="mw-section-head"><div><h2>Категории и маршрутизация</h2><p className="mw-muted">Эксперт по умолчанию получает новые обращения этой категории автоматически.</p></div><button className="mw-primary" onClick={()=>setForm({code:'',title:'',active:true,expertId:''})}>+ Категория</button></div>{error&&<p className="mw-error">{error}</p>}{form&&<form className="mw-editor" onSubmit={async e=>{e.preventDefault();try{await api('/admin/categories',form);setForm(null);await load()}catch(e:any){setError(e.message)}}}><label>Код<input required value={form.code} onChange={e=>setForm({...form,code:e.target.value})}/></label><label>Название<input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>Назначение<select value={form.expertId} onChange={e=>setForm({...form,expertId:e.target.value})}><option value="">Ручное назначение оператором</option>{experts.map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select></label><label className="mw-check"><input type="checkbox" checked={form.active} onChange={e=>setForm({...form,active:e.target.checked})}/>Показывать заявителям</label><div className="mw-inline"><button className="mw-primary">Сохранить</button><button type="button" className="mw-btn" onClick={()=>setForm(null)}>Отмена</button></div></form>}<table><thead><tr><th>Категория</th><th>Маршрут</th><th>Публикация</th><th></th></tr></thead><tbody>{items.map(c=><tr key={c.id}><td>{c.title}</td><td>{experts.find(e=>e.id===c.default_expert_id)?.name||'Очередь оператора'}</td><td>{c.active?'Включена':'Скрыта'}</td><td><button className="mw-link" onClick={()=>setForm({code:c.code,title:c.title,active:c.active,expertId:c.default_expert_id||''})}>Настроить</button></td></tr>)}</tbody></table></section>}

function RoutingAdmin({experts}:{experts:any[]}){
 const [categories,setCategories]=useState<any[]>([]),[groups,setGroups]=useState<any[]>([]),[categoryForm,setCategoryForm]=useState<any>(null),[groupForm,setGroupForm]=useState<any>(null),[error,setError]=useState('')
 async function load(){const [c,g]=await Promise.all([api('/admin/categories'),api('/admin/groups')]);setCategories(c.items||[]);setGroups(g.items||[])}
 useEffect(()=>{load().catch(e=>setError(e.message))},[])
 return <div className="mw-admin-stack">
  <section className="mw-panel mw-pad"><div className="mw-section-head"><div><h2>Группы специалистов</h2><p className="mw-muted">Лимит задаёт максимальное число активных обращений на одного эксперта.</p></div><button className="mw-primary" onClick={()=>setGroupForm({name:'',maxActive:20,active:true,expertIds:[]})}>+ Группа</button></div>{groupForm&&<form className="mw-editor" onSubmit={async e=>{e.preventDefault();try{await api('/admin/groups',groupForm);setGroupForm(null);await load()}catch(e:any){setError(e.message)}}}><label>Название<input required value={groupForm.name} onChange={e=>setGroupForm({...groupForm,name:e.target.value})}/></label><label>Лимит активных на эксперта<input type="number" min="1" max="500" required value={groupForm.maxActive} onChange={e=>setGroupForm({...groupForm,maxActive:Number(e.target.value)})}/></label><fieldset><legend>Участники</legend>{experts.map(e=><label className="mw-check" key={e.id}><input type="checkbox" checked={groupForm.expertIds.includes(e.id)} onChange={x=>setGroupForm({...groupForm,expertIds:x.target.checked?[...groupForm.expertIds,e.id]:groupForm.expertIds.filter((id:string)=>id!==e.id)})}/>{e.name} · {e.active_count||0} активных</label>)}</fieldset><label className="mw-check"><input type="checkbox" checked={groupForm.active} onChange={e=>setGroupForm({...groupForm,active:e.target.checked})}/>Группа активна</label><div className="mw-inline"><button className="mw-primary">Сохранить</button><button type="button" className="mw-btn" onClick={()=>setGroupForm(null)}>Отмена</button></div></form>}<table><thead><tr><th>Группа</th><th>Лимит</th><th>Участники</th><th></th></tr></thead><tbody>{groups.map(g=><tr key={g.id}><td>{g.name}</td><td>{g.max_active_per_expert}</td><td>{g.expert_ids.length}</td><td><button className="mw-link" onClick={()=>setGroupForm({id:g.id,name:g.name,maxActive:g.max_active_per_expert,active:g.active,expertIds:g.expert_ids})}>Настроить</button></td></tr>)}</tbody></table></section>
  <section className="mw-panel mw-pad"><div className="mw-section-head"><div><h2>Категории и правила</h2><p className="mw-muted">Система предложит оператору наименее загруженного эксперта группы, но решение останется за человеком.</p></div><button className="mw-primary" onClick={()=>setCategoryForm({code:'',title:'',active:true,groupId:''})}>+ Категория</button></div>{error&&<p className="mw-error">{error}</p>}{categoryForm&&<form className="mw-editor" onSubmit={async e=>{e.preventDefault();try{await api('/admin/categories',categoryForm);setCategoryForm(null);await load()}catch(e:any){setError(e.message)}}}><label>Код<input required disabled={!!categoryForm.id} value={categoryForm.code} onChange={e=>setCategoryForm({...categoryForm,code:e.target.value})}/></label><label>Название<input required value={categoryForm.title} onChange={e=>setCategoryForm({...categoryForm,title:e.target.value})}/></label><label>Группа специалистов<select value={categoryForm.groupId} onChange={e=>setCategoryForm({...categoryForm,groupId:e.target.value})}><option value="">Без правила — очередь оператора</option>{groups.filter(g=>g.active).map(g=><option value={g.id} key={g.id}>{g.name}</option>)}</select></label><label className="mw-check"><input type="checkbox" checked={categoryForm.active} onChange={e=>setCategoryForm({...categoryForm,active:e.target.checked})}/>Показывать заявителям</label><div className="mw-inline"><button className="mw-primary">Сохранить</button><button type="button" className="mw-btn" onClick={()=>setCategoryForm(null)}>Отмена</button></div></form>}<table><thead><tr><th>Категория</th><th>Подсказка</th><th>Публикация</th><th></th></tr></thead><tbody>{categories.map(c=><tr key={c.id}><td>{c.title}</td><td>{c.group_name||'Без правила'}</td><td>{c.active?'Включена':'Скрыта'}</td><td><button className="mw-link" onClick={()=>setCategoryForm({id:c.id,code:c.code,title:c.title,active:c.active,groupId:c.group_id||''})}>Настроить</button></td></tr>)}</tbody></table></section>
 </div>
}

function AuditLog(){const [items,setItems]=useState<any[]>([]),[error,setError]=useState('');useEffect(()=>{api('/admin/audit').then(d=>setItems(d.items||[])).catch(e=>setError(e.message))},[]);return <section className="mw-panel mw-pad"><div className="mw-section-head"><div><h2>Журнал действий</h2><p className="mw-muted">Административные причины и служебные действия без текстов обращений и переписки.</p></div></div>{error&&<p className="mw-error">{error}</p>}<table><thead><tr><th>Время</th><th>Сотрудник</th><th>Действие</th><th>Причина</th></tr></thead><tbody>{items.map(e=><tr key={e.id}><td>{new Date(e.created_at).toLocaleString('ru-RU')}</td><td>{e.actor}</td><td>{actions[e.action]||e.action}</td><td>{e.reason||'—'}</td></tr>)}</tbody></table></section>}
